//
// Created by Philip Tschiemer on 13.06.20.
//

#ifndef OCAC_OCACOPTS_H
#define OCAC_OCACOPTS_H

#define OCAC_PLATFORM_ASSERT(message) { printf("ASSERT FAILED: %s\n", message); exit(1);}

//#define OCAC_DEVICE_MANUFACTURER_NAME "filou.se"
//#define OCAC_DEVICE_MANUFACTURER_NAME_LEN 9

//#define OCAC_DEVICE_MODEL_NAME "Secret Prototype"
//#define OCAC_DEVICE_MODEL_NAME_LEN 17

//#define OCAC_DEVICE_MODEL_VERSION "1.0.0"
//#define OCAC_DEVICE_MODEL_VERSION_LEN 6

//#define OCAC_OBJ_DEVICEMANAGER_DEVICENAME_DEFAULT
//OCAC_OBJ_DEVICEMANAGER_DEVICENAME


//#define OCAC_DEVICE_MANUFACTURER_CODE {0xF0,0x0B,0xA5}
//#define OCAC_DEVICE_MODEL_CODE {0x13,0x37,0xBA,0xBE}

//#define OCAC_DEVICE_SERIAL_DEFAULT "1234567890"
//#define OCAC_DEVICE_SERIAL_UTF8_LEN 10
//#define OCAC_DEVICE_SERIAL_LEN 11



#endif //OCAC_OCACOPTS_H
