//
// Created by Philip Tschiemer on 13.06.20.
//

#ifndef OCAC_OPT_H
#define OCAC_OPT_H


/*
 * Include user defined options first. Anything not defined in these files
 * will be set to standard values. Override anything you don't like!
 */
#include "ocacopts.h"
#include "ocac/debug.h"


/**************************************************
 * Required option check
 **/

#if !defined(OCAC_DEVICE_MANUFACTURER_NAME) || !defined(OCAC_DEVICE_MANUFACTURER_NAME_LEN)
#error OCAC_DEVICE_MANUFACTURER_NAME and OCAC_DEVICE_MANUFACTURER_NAME_LEN are required
#endif

#if !defined(OCAC_DEVICE_MODEL_NAME) || !defined(OCAC_DEVICE_MODEL_NAME_LEN)
#error OCAC_DEVICE_MODEL_NAME and OCAC_DEVICE_MODEL_NAME_LEN are required
#endif

#if !defined(OCAC_DEVICE_MODEL_VERSION) || !defined(OCAC_DEVICE_MODEL_VERSION_LEN)
#error OCAC_DEVICE_MODEL_VERSION and OCAC_DEVICE_MODEL_VERSION_LEN are required
#endif

#if !defined(OCAC_DEVICE_MANUFACTURER_CODE) || !defined(OCAC_DEVICE_MODEL_CODE)
#error OCAC_DEVICE_MANUFACTURER_CODE and OCAC_DEVICE_MODEL_CODE are required
#endif

#if !defined(OCAC_DEVICE_SERIAL_DEFAULT) || !defined(OCAC_DEVICE_SERIAL_LEN)
#error OCAC_DEVICE_SERIAL_DEFAULT and OCAC_DEVICE_SERIAL_LEN are required
#endif




/**************************************************
 * OCC Datatypes
 **/

#ifndef OCAC_OCC_FRAMEWORK_CLASSID_SIZE
#define OCAC_OCC_FRAMEWORK_CLASSID_SIZE 8
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_MANUFACTURER_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_MANUFACTURER_MAXLEN 32
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_NAME_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_NAME_MAXLEN 32
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_VERSION_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_VERSION_MAXLEN 16
#endif

#ifndef OCAC_OCC_NETWORK_HOSTID_MAXLEN
#define OCAC_OCC_NETWORK_HOSTID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_NODEID_MAXLEN
#define OCAC_OCC_NETWORK_NODEID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_ADDR_MAXLEN
#define OCAC_OCC_NETWORK_ADDR_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMID_MAXLEN
#define OCAC_OCC_NETWORK_STREAMID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMPARAM_MAXLEN
#define OCAC_OCC_NETWORK_STREAMPARAM_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMCONNID_MAXLEN
#define OCAC_OCC_NETWORK_STREAMCONNID_MAXLEN 128
#endif


/**************************************************
 * OCAC Class & Object Configuration
 **/

//#define OCAC_NO_PROPERTIES

//#define OCAC_NO_EVENTS


#ifndef OCAC_CLASS_NAME
#define OCAC_CLASS_NAME(name)  name ## _class
#endif

#ifndef OCAC_OBJ_NAME
#define OCAC_OBJ_NAME(name) name ## _obj
#endif


#ifndef OCAC_OCA_VERSION
#define OCAC_OCA_VERSION 2
#endif



/**************************************************
 * OCAC Class implementation specific
 **/

#ifndef OCAC_CLASS_COMMON_ATTRIBUTES
#define OCAC_CLASS_COMMON_ATTRIBUTES
#endif

/** OcaRoot **/

#ifndef OCAC_CLASS_ROOT_ATTRIBUTES
#define OCAC_CLASS_ROOT_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_ROOT_ROLE_MAXLEN
#define OCAC_OBJ_ROOT_ROLE_MAXLEN 10
#endif

#ifndef OCAC_OBJ_ROOT_DEF_CUSTOM
#define OCAC_OBJ_ROOT_DEF_CUSTOM
#endif

/** OcaManager **/

#ifndef OCAC_CLASS_MANAGER_ATTRIBUTES
#define OCAC_CLASS_MANAGER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_MANAGER_NAME_MAXLEN
#define OCAC_OBJ_MANAGER_NAME_MAXLEN 20
#endif


#ifndef OCAC_OBJ_DEVICEMANAGER_DEF_CUSTOM
#define OCAC_OBJ_DEVICEMANAGER_DEF_CUSTOM
#endif

/** OcaDeviceManager **/

#ifndef OCAC_CLASS_DEVICEMANAGER_ATTRIBUTES
#define OCAC_CLASS_DEVICEMANAGER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_DEVICENAME_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_DEVICENAME_MAXLEN 32
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_MAXLEN 32
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_DEFAULT {0, ""}
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_MESSAGE_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_MESSAGE_MAXLEN 128
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_MESSAGE_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_MESSAGE_DEFAULT {8, "ILOVEYOU"}
#endif


#endif //OCAC_OPT_H
