//
// Created by Philip Tschiemer on 13.06.20.
//

#ifndef OCAC_OPT_H
#define OCAC_OPT_H


/*
 * Include user defined options first. Anything not defined in these files
 * will be set to standard values. Override anything you don't like!
 */
#include "ocacopts.h"
#include "ocac/debug.h"


#ifndef OCAC_USE_MANAGER_SECURITY
#define OCAC_USE_MANAGER_SECURITY 1
#endif

#ifndef OCAC_USE_MANAGER_FIRMWARE
#define OCAC_USE_MANAGER_FIRMWARE 1
#endif

#ifndef OCAC_USE_MANAGER_SUBSCRIPTION
#define OCAC_USE_MANAGER_SUBSCRIPTION 1
#endif

#ifndef OCAC_USE_MANAGER_POWER
#define OCAC_USE_MANAGER_POWER 1
#endif

#ifndef OCAC_USE_MANAGER_NETWORK
#define OCAC_USE_MANAGER_NETWORK 1
#endif

#ifndef OCAC_USE_MANAGER_MEDIACLOCK
#define OCAC_USE_MANAGER_MEDIACLOCK 1
#endif

#ifndef OCAC_USE_MANAGER_LIBRARY
#define OCAC_USE_MANAGER_LIBRARY 1
#endif

#ifndef OCAC_USE_MANAGER_AUDIOPROCESSING
#define OCAC_USE_MANAGER_AUDIOPROCESSING 1
#endif

#ifndef OCAC_USE_MANAGER_DEVICETIME
#define OCAC_USE_MANAGER_DEVICETIME 1
#endif

#ifndef OCAC_USE_MANAGER_TASK
#define OCAC_USE_MANAGER_TASK 1
#endif

#ifndef OCAC_USE_MANAGER_CODING
#define OCAC_USE_MANAGER_CODING 1
#endif

#ifndef OCAC_USE_MANAGER_DIAGNOSTIC
#define OCAC_USE_MANAGER_DIAGNOSTIC 1
#endif

/**************************************************
 * OCC Datatypes
 **/

#ifndef OCAC_OCC_FRAMEWORK_CLASSID_SIZE
#define OCAC_OCC_FRAMEWORK_CLASSID_SIZE 8
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_MANUFACTURER_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_MANUFACTURER_MAXLEN 32
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_NAME_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_NAME_MAXLEN 32
#endif

#ifndef OCAC_OCC_MANAGEMENT_MODEL_VERSION_MAXLEN
#define OCAC_OCC_MANAGEMENT_MODEL_VERSION_MAXLEN 16
#endif

#ifndef OCAC_OCC_NETWORK_HOSTID_MAXLEN
#define OCAC_OCC_NETWORK_HOSTID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_NODEID_MAXLEN
#define OCAC_OCC_NETWORK_NODEID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_ADDR_MAXLEN
#define OCAC_OCC_NETWORK_ADDR_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMID_MAXLEN
#define OCAC_OCC_NETWORK_STREAMID_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMPARAM_MAXLEN
#define OCAC_OCC_NETWORK_STREAMPARAM_MAXLEN 128
#endif

#ifndef OCAC_OCC_NETWORK_STREAMCONNID_MAXLEN
#define OCAC_OCC_NETWORK_STREAMCONNID_MAXLEN 128
#endif


/**************************************************
 * OCAC Class & Object Configuration
 **/

//#define OCAC_NO_PROPERTIES

//#define OCAC_NO_EVENTS


#ifndef OCAC_CLASS_NAME
#define OCAC_CLASS_NAME(name)  name ## _class
#endif

#ifndef OCAC_OBJ_NAME
#define OCAC_OBJ_NAME(name) name ## _obj
#endif


#ifndef OCAC_OCA_VERSION
#define OCAC_OCA_VERSION 2
#endif



/**************************************************
 * OCAC Class implementation specific
 **/

#ifndef OCAC_CLASS_COMMON_ATTRIBUTES
#define OCAC_CLASS_COMMON_ATTRIBUTES
#endif

/** OcaRoot **/

#ifndef OCAC_CLASS_ROOT_ATTRIBUTES
#define OCAC_CLASS_ROOT_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_ROOT_ROLE_MAXLEN
#define OCAC_OBJ_ROOT_ROLE_MAXLEN 10
#endif

#ifndef OCAC_OBJ_ROOT_DEF_CUSTOM
#define OCAC_OBJ_ROOT_DEF_CUSTOM
#endif

/** OcaManager **/

#ifndef OCAC_CLASS_MANAGER_ATTRIBUTES
#define OCAC_CLASS_MANAGER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_MANAGER_NAME_MAXLEN
#define OCAC_OBJ_MANAGER_NAME_MAXLEN 20
#endif


#ifndef OCAC_OBJ_DEVICEMANAGER_DEF_CUSTOM
#define OCAC_OBJ_DEVICEMANAGER_DEF_CUSTOM
#endif

/** Worker **/

#ifndef OCAC_CLASS_WORKER_ATTRIBUTES
#define OCAC_CLASS_WORKER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_OBJ_WORKER_DEF_LABEL_LEN
#define OCAC_OBJ_WORKER_DEF_LABEL_LEN 32
#endif

/** OcaDeviceManager **/

#ifndef OCAC_CLASS_DEVICEMANAGER_ATTRIBUTES
#define OCAC_CLASS_DEVICEMANAGER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif

#ifndef OCAC_DEVICE_MANUFACTURER_NAME
#define OCAC_DEVICE_MANUFACTURER_NAME "filou.se"
#endif
#ifndef OCAC_DEVICE_MANUFACTURER_NAME_LEN
#define OCAC_DEVICE_MANUFACTURER_NAME_LEN sizeof(OCAC_DEVICE_MANUFACTURER_NAME)
#endif
#ifndef OCAC_DEVICE_MANUFACTURER_NAME_UTF8_LEN
#define OCAC_DEVICE_MANUFACTURER_NAME_UTF8_LEN (OCAC_DEVICE_MANUFACTURER_NAME_LEN - 1)
#endif

#ifndef OCAC_DEVICE_MODEL_NAME
#define OCAC_DEVICE_MODEL_NAME "Secret Prototype"
#endif
#ifndef OCAC_DEVICE_MODEL_NAME_LEN
#define OCAC_DEVICE_MODEL_NAME_LEN sizeof(OCAC_DEVICE_MODEL_NAME)
#endif
#ifndef OCAC_DEVICE_MODEL_NAME_UTF8_LEN
#define OCAC_DEVICE_MODEL_NAME_UTF8_LEN (OCAC_DEVICE_MODEL_NAME_LEN-1)
#endif

#ifndef OCAC_DEVICE_MODEL_VERSION
#define OCAC_DEVICE_MODEL_VERSION "1.0.0~alpha"
#endif
#ifndef OCAC_DEVICE_MODEL_VERSION_LEN
#define OCAC_DEVICE_MODEL_VERSION_LEN sizeof(OCAC_DEVICE_MODEL_VERSION)
#endif
#ifndef OCAC_DEVICE_MODEL_VERSION_UTF8_LEN
#define OCAC_DEVICE_MODEL_VERSION_UTF8_LEN (OCAC_DEVICE_MODEL_VERSION_LEN-1)
#endif

// (unique) IEEE Manufacturer ID
#ifndef OCAC_DEVICE_MANUFACTURER_CODE
#define OCAC_DEVICE_MANUFACTURER_CODE {0xF0,0x0B,0xA5}
#endif

#ifndef OCAC_DEVICE_MODEL_CODE
#define OCAC_DEVICE_MODEL_CODE {0x13,0x37,0xBA,0xBE}
#endif


#ifndef OCAC_DEVICE_SERIAL_DEFAULT
#define OCAC_DEVICE_SERIAL_DEFAULT "1234:5678:90"
#endif

#ifndef OCAC_DEVICE_SERIAL_LEN
#define OCAC_DEVICE_SERIAL_LEN sizeof(OCAC_DEVICE_SERIAL_DEFAULT)
#endif
#ifndef OCAC_DEVICE_SERIAL_UTF8_LEN
#define OCAC_DEVICE_SERIAL_UTF8_LEN (OCAC_DEVICE_SERIAL_LEN-1)
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_DEVICENAME_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_DEVICENAME_MAXLEN 32
#endif
#ifndef OCAC_OBJ_DEVICEMANAGER_DEVICENAME_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_DEVICENAME_DEFAULT {13, "Remote Device"}
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_MAXLEN 32
#endif
#ifndef OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_USERINVENTORYCODE_DEFAULT {0, ""}
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_MESSAGE_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_MESSAGE_MAXLEN 128
#endif
#ifndef OCAC_OBJ_DEVICEMANAGER_MESSAGE_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_MESSAGE_DEFAULT {7, "I \xe2\x99\xa1 YOU"}
#endif

#ifndef OCAC_OBJ_DEVICEMANAGER_REVISIONID_DEFAULT
#define OCAC_OBJ_DEVICEMANAGER_REVISIONID_DEFAULT "1"
#endif
#ifndef OCAC_OBJ_DEVICEMANAGER_REVISIONID_MAXLEN
#define OCAC_OBJ_DEVICEMANAGER_REVISIONID_MAXLEN 16
#endif


/** OcaSubscriptionManager **/

#ifndef OCAC_CLASS_SUBSCRIPTIONMANAGER_ATTRIBUTES
#define OCAC_CLASS_SUBSCRIPTIONMANAGER_ATTRIBUTES OCAC_CLASS_COMMON_ATTRIBUTES
#endif


#endif //OCAC_OPT_H
