//
// Created by Philip Tschiemer on 13.06.20.
//

#ifndef OCAC_OCC_CLASSES_MANAGERS_ABSTRACT_H
#define OCAC_OCC_CLASSES_MANAGERS_ABSTRACT_H

#include "ocac/occ/classes/root.h"

#ifdef __cplusplus
extern "C" {
#endif

#define OCAC_CLASS_MANAGER_ID           {2, {1,3}}
#define OCAC_CLASS_MANAGER_VERSION      1


#ifdef OCAC_CLASS_NO_METHOD_OVERRIDE
#define OCAC_CLASS_MANAGER_METHODS_DEFAULT     0
#else
#define OCAC_CLASS_MANAGER_METHODS_DEFAULT     OCAC_CLASS_ROOT_METHODS
#endif




#if OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_CUSTOM

#error include some file here

#elif OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_MIN || OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_MAX

#define OCAC_CLASS_MANAGER_PROPERTIES 0
#define OCAC_CLASS_MANAGER_02pXX

#define OCAC_CLASS_MANAGER_METHODS OCAC_CLASS_MANAGER_METHODS_DEFAULT
#define OCAC_CLASS_MANAGER_02mXX

#define OCAC_CLASS_MANAGER_EVENTS 0
#define OCAC_CLASS_MANAGER_02eXX

#endif


#ifdef OCAC_CLASS_NO_METHOD_OVERRIDE
#define OCAC_CLASS_MANAGER_XXmXX \
    OCAC_CLASS_MANAGER_02mXX
#else
#define OCAC_CLASS_MANAGER_XXmXX \
    OCAC_CLASS_ROOT_01mXX, \
    OCAC_CLASS_MANAGER_02mXX
#endif


#ifndef OCAC_CLASS_NO_DEFAULT_DEFINITION
OCAC_CLASS_DEF_BEGIN(OcaManager)
    OCAC_CLASS_DEF_DATA(OCAC_CLASS_MANAGER_PROPERTIES, OCAC_CLASS_MANAGER_METHODS, OCAC_CLASS_MANAGER_EVENTS)
OCAC_CLASS_DEF_END(OcaManager)
#endif



#define OCAC_OBJ_MANAGER_DEF_MINMAX \
    const char name[OCAC_OBJ_MANAGER_NAME_MAXLEN]; // Needed for manager descripter (see device manager) \

#if OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_CUSTOM
#define OCAC_OBJ_MANAGER_DEF \
    OCAC_OBJ_MANAGER_DEF_CUSTOM
#elif OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_MIN || OCAC_CLASS_DEFINITION == OCAC_CLASS_DEFINITION_MAX
#define OCAC_OBJ_MANAGER_DEF \
    OCAC_OBJ_MANAGER_DEF_MINMAX \
    OCAC_OBJ_MANAGER_DEF_CUSTOM
#endif

#ifndef OCAC_OBJ_NO_DEFAULT_DEFINITION
OCAC_OBJ_DEF_BEGIN(OcaManager)
    OCAC_OBJ_ROOT_DEF
    OCAC_OBJ_MANAGER_DEF
OCAC_OBJ_DEF_END(OcaManager)
#endif


#ifndef OCAC_CLASS_NO_DEFAULT_ALLOCATION
extern OCAC_CLASS_TYPE(OcaManager) OCAC_CLASS_NAME(OcaManager);
#endif

//#ifndef OCAC_OBJ_NO_DEFAULT_ALLOCATION
//extern OCAC_OBJ_TYPE(OcaManager) OCAC_OBJ_NAME(OcaManager);
//#endif


#ifdef DEBUG
void ocac_dump_manager(OCAC_OBJ_BASE * obj);
#endif

#ifdef __cplusplus
}
#endif

#endif //OCAC_OCC_CLASSES_MANAGERS_ABSTRACT_H
