//
// Created by Philip Tschiemer on 20.06.20.
//

#include <string.h>
#include "ocac/utf8.h"



void generate(char * type, char * value){


    u8_t tmp[1024];
    u16_t size = 0;

    if (strcmp(type, "string") == 0)
    {
        u16_t len = ocac_utf8_strlen((u8_t*)value, strlen(value));
        s32_t bytes = ocac_utf8_cpyn(&tmp[2], (u8_t*)value, len, sizeof(tmp));

        if (bytes < 0){
            fprintf(stderr, "ERROR utf8_cpyn %d\n", bytes);
            exit(EXIT_FAILURE);
        }

        *(u16_t*)tmp = htons(len);

        size = sizeof(u16_t) + bytes;
    }

    if (strcmp(type, "bool") == 0)
    {
        tmp[0] = !!atoi(value);
        size = 1;
    }

    if (size == 0){
        fprintf(stderr, "ERROR unrecognized type %s\n", type);
        exit(EXIT_FAILURE);
    }

    if (size > 0){
        for(int i = 0; i < size; i++){
            printf("%02hhX", tmp[i]);
        }
    }

}

int main(int argc, char * argv[]){

    if (argc == 2 && strcmp(argv[1], "-h") == 0){
        printf("Usage: %s [<oca-type> <value> ..]\n", argv[0]);
        printf("Prints generated byte sequence in HEX to STDOUT\n");
        printf("If no type/value pair is given reads from STDIN until EOF\n");
        return EXIT_SUCCESS;
    }

    if (argc > 1){
        if ( (argc - 1) % 2 == 1){
            fprintf(stderr, "ERROR requires <oca-type> <value> pairs");
            return EXIT_FAILURE;
        }

        for (int i = 1; i < argc; i+=2){
            generate(argv[i], argv[i+1]);
        }
    }

    fclose(stdout);


    return EXIT_SUCCESS;
}